name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --file src/main/docker/Dockerfile.jvm -t devnexus2024-monolith .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag devnexus2024-monolith ${{ secrets.DOCKERHUB_USERNAME }}/devnexus2024-monolith:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devnexus2024-monolith:latest